"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
exports.__esModule = true;
var express_1 = require("express");
var userRoutes_1 = __importDefault(require("./userRoutes"));
var authRoutes_1 = __importDefault(require("./authRoutes"));
var settingRoutes_1 = __importDefault(require("./settingRoutes"));
var contactRoutes_1 = __importDefault(require("./contactRoutes"));
var ticketRoutes_1 = __importDefault(require("./ticketRoutes"));
var userPagePermissionRoutes_1 = __importDefault(require("./userPagePermissionRoutes"));
var whatsappRoutes_1 = __importDefault(require("./whatsappRoutes"));
var whatsappCoexistenceRoutes_1 = __importDefault(require("./whatsappCoexistenceRoutes"));
var whatsappOfficialRoutes_1 = __importDefault(require("./whatsappOfficialRoutes"));
var messageRoutes_1 = __importDefault(require("./messageRoutes"));
var whatsappSessionRoutes_1 = __importDefault(require("./whatsappSessionRoutes"));
var queueRoutes_1 = __importDefault(require("./queueRoutes"));
var companyRoutes_1 = __importDefault(require("./companyRoutes"));
var planRoutes_1 = __importDefault(require("./planRoutes"));
var ticketNoteRoutes_1 = __importDefault(require("./ticketNoteRoutes"));
var quickMessageRoutes_1 = __importDefault(require("./quickMessageRoutes"));
var helpRoutes_1 = __importDefault(require("./helpRoutes"));
var dashboardRoutes_1 = __importDefault(require("./dashboardRoutes"));
var scheduleRoutes_1 = __importDefault(require("./scheduleRoutes"));
var tagRoutes_1 = __importDefault(require("./tagRoutes"));
var contactListRoutes_1 = __importDefault(require("./contactListRoutes"));
var contactListItemRoutes_1 = __importDefault(require("./contactListItemRoutes"));
var campaignRoutes_1 = __importDefault(require("./campaignRoutes"));
var campaignSettingRoutes_1 = __importDefault(require("./campaignSettingRoutes"));
var announcementRoutes_1 = __importDefault(require("./announcementRoutes"));
var chatRoutes_1 = __importDefault(require("./chatRoutes"));
var queueIntegrationRoutes_1 = __importDefault(require("./queueIntegrationRoutes"));
var chatBotRoutes_1 = __importDefault(require("./chatBotRoutes"));
var webHookRoutes_1 = __importDefault(require("./webHookRoutes"));
var webhookListRoutes_1 = __importDefault(require("./webhookListRoutes"));
var subScriptionRoutes_1 = __importDefault(require("./subScriptionRoutes"));
var invoicesRoutes_1 = __importDefault(require("./invoicesRoutes"));
var faturasRoutes_1 = __importDefault(require("./faturasRoutes"));
var apiRoutes_1 = __importDefault(require("./apiRoutes"));
var versionRoutes_1 = __importDefault(require("./versionRoutes"));
var filesRoutes_1 = __importDefault(require("./filesRoutes"));
var queueOptionRoutes_1 = __importDefault(require("./queueOptionRoutes"));
var ticketTagRoutes_1 = __importDefault(require("./ticketTagRoutes"));
var apiCompanyRoutes_1 = __importDefault(require("./api/apiCompanyRoutes"));
var apiContactRoutes_1 = __importDefault(require("./api/apiContactRoutes"));
var apiMessageRoutes_1 = __importDefault(require("./api/apiMessageRoutes"));
var externalClientRoutes_1 = __importDefault(require("./api/externalClientRoutes"));
var externalContactRoutes_1 = __importDefault(require("./api/externalContactRoutes"));
var externalTagRoutes_1 = __importDefault(require("./api/externalTagRoutes"));
var externalProductRoutes_1 = __importDefault(require("./api/externalProductRoutes"));
var externalProductCategoryRoutes_1 = __importDefault(require("./api/externalProductCategoryRoutes"));
var externalServiceRoutes_1 = __importDefault(require("./api/externalServiceRoutes"));
var externalQueueRoutes_1 = __importDefault(require("./api/externalQueueRoutes"));
var externalNegocioRoutes_1 = __importDefault(require("./api/externalNegocioRoutes"));
var googleSheetsRoutes_1 = __importDefault(require("./googleSheetsRoutes"));
var externalTagKanbanRoutes_1 = __importDefault(require("./api/externalTagKanbanRoutes"));
var externalProjectRoutes_1 = __importDefault(require("./api/externalProjectRoutes"));
var externalProjectTaskRoutes_1 = __importDefault(require("./api/externalProjectTaskRoutes"));
var externalUserRoutes_1 = __importDefault(require("./api/externalUserRoutes"));
var externalTicketRoutes_1 = __importDefault(require("./api/externalTicketRoutes"));
var externalWhatsappRoutes_1 = __importDefault(require("./api/externalWhatsappRoutes"));
var externalFaturaRoutes_1 = __importDefault(require("./api/externalFaturaRoutes"));
var companySettingsRoutes_1 = __importDefault(require("./companySettingsRoutes"));
var companyDocumentRoutes_1 = __importDefault(require("./companyDocumentRoutes"));
var promptRouter_1 = __importDefault(require("./promptRouter"));
var knowledgeBaseRouter_1 = __importDefault(require("./knowledgeBaseRouter"));
var iaWorkflowRoutes_1 = __importDefault(require("./iaWorkflowRoutes"));
var statisticsRoutes_1 = __importDefault(require("./statisticsRoutes"));
var ScheduledMessagesRoutes_1 = __importDefault(require("./ScheduledMessagesRoutes"));
var flowDefaultRoutes_1 = __importDefault(require("./flowDefaultRoutes"));
var webHookRoutes_2 = __importDefault(require("./webHookRoutes"));
var flowBuilderRoutes_1 = __importDefault(require("./flowBuilderRoutes"));
var flowCampaignRoutes_1 = __importDefault(require("./flowCampaignRoutes"));
var forgotPasswordRoutes_1 = __importDefault(require("./forgotPasswordRoutes"));
var imaginasoftRoutes_1 = __importDefault(require("./imaginasoftRoutes"));
var clinicChatRoutes_1 = __importDefault(require("./clinicChatRoutes"));
var negocioRoutes_1 = __importDefault(require("./negocioRoutes"));
var produtoRoutes_1 = __importDefault(require("./produtoRoutes"));
var ferramentaRoutes_1 = __importDefault(require("./ferramentaRoutes"));
var googleCalendarRoutes_1 = __importDefault(require("./googleCalendarRoutes"));
var userGoogleCalendarRoutes_1 = __importDefault(require("./userGoogleCalendarRoutes"));
var facebookOAuthRoutes_1 = __importDefault(require("./facebookOAuthRoutes"));
var googleBusinessRoutes_1 = __importDefault(require("./googleBusinessRoutes"));
var fiscalRoutes_1 = __importDefault(require("./fiscalRoutes"));
var aiSuggestionRoutes_1 = __importDefault(require("./aiSuggestionRoutes"));
var aiCreditsRoutes_1 = __importDefault(require("./aiCreditsRoutes"));
// import mobileWebhookRoutes from "./mobileWebhookRoutes";
var emailRoutes_1 = __importDefault(require("./emailRoutes"));
var tutorialVideoRoutes_1 = __importDefault(require("./tutorialVideoRoutes"));
var sliderHomeRoutes_1 = __importDefault(require("./sliderHomeRoutes"));
var profissionalRoutes_1 = __importDefault(require("./profissionalRoutes"));
var servicoRoutes_1 = __importDefault(require("./servicoRoutes"));
var crmLeadRoutes_1 = __importDefault(require("./crmLeadRoutes"));
var crmClientRoutes_1 = __importDefault(require("./crmClientRoutes"));
var automationRoutes_1 = __importDefault(require("./automationRoutes"));
var financeiroFaturaRoutes_1 = __importDefault(require("./financeiroFaturaRoutes"));
var financeiroPagamentoRoutes_1 = __importDefault(require("./financeiroPagamentoRoutes"));
var financeiroCategoriaRoutes_1 = __importDefault(require("./financeiroCategoriaRoutes"));
var financeiroDespesaRoutes_1 = __importDefault(require("./financeiroDespesaRoutes"));
var financeiroFornecedorRoutes_1 = __importDefault(require("./financeiroFornecedorRoutes"));
var financeiroPagamentoDespesaRoutes_1 = __importDefault(require("./financeiroPagamentoDespesaRoutes"));
var paymentSettingRoutes_1 = __importDefault(require("./paymentSettingRoutes"));
var integrationSettingRoutes_1 = __importDefault(require("./integrationSettingRoutes"));
var aiIntegrationRoutes_1 = __importDefault(require("./aiIntegrationRoutes"));
var taskRoutes_1 = __importDefault(require("./taskRoutes"));
var emailAccountRoutes_1 = __importDefault(require("./emailAccountRoutes"));
var companyApiKeyRoutes_1 = __importDefault(require("./companyApiKeyRoutes"));
var paymentGatewayWebhookRoutes_1 = __importDefault(require("./paymentGatewayWebhookRoutes"));
var checkoutRoutes_1 = __importDefault(require("./checkoutRoutes"));
var asaasRoutes_1 = __importDefault(require("./asaasRoutes"));
var scheduledDispatcherRoutes_1 = __importDefault(require("./scheduledDispatcherRoutes"));
var projectRoutes_1 = __importDefault(require("./projectRoutes"));
var userScheduleRoutes_1 = __importDefault(require("./userScheduleRoutes"));
var appointmentRoutes_1 = __importDefault(require("./appointmentRoutes"));
var externalApiRoutes_1 = __importDefault(require("./externalApiRoutes"));
var hubChannelRoutes_1 = __importDefault(require("../HubEcosystem/routes/hubChannelRoutes"));
var followUpRoutes_1 = __importDefault(require("./followUpRoutes"));
var affiliateRoutes_1 = __importDefault(require("./affiliateRoutes"));
var couponRoutes_1 = __importDefault(require("./couponRoutes"));
var hubMessageRoutes_1 = __importDefault(require("../HubEcosystem/routes/hubMessageRoutes"));
var hubWebhookRoutes_1 = __importDefault(require("../HubEcosystem/routes/hubWebhookRoutes"));
var contactSettingsRoutes_1 = __importDefault(require("./contactSettingsRoutes"));
var contactAnalyticsRoutes_1 = __importDefault(require("./contactAnalyticsRoutes"));
var notificationRoutes_1 = __importDefault(require("./notificationRoutes"));
var callRecordRoutes_1 = __importDefault(require("./callRecordRoutes"));
var translationRoutes_1 = __importDefault(require("./translationRoutes"));
var serviceOrderRoutes_1 = __importDefault(require("./serviceOrderRoutes"));
var groupRoutes_1 = __importDefault(require("./groupRoutes"));
var hostiNotasRoutes_1 = __importDefault(require("./hostiNotasRoutes"));
var whatsappWidgetRoutes_1 = __importDefault(require("./whatsappWidgetRoutes"));
var routes = (0, express_1.Router)();
routes.use(userRoutes_1["default"]);
routes.use("/auth", authRoutes_1["default"]);
routes.use("/api/messages", apiRoutes_1["default"]);
routes.use(settingRoutes_1["default"]);
routes.use(contactRoutes_1["default"]);
routes.use(groupRoutes_1["default"]);
routes.use(ticketRoutes_1["default"]);
routes.use(whatsappRoutes_1["default"]);
routes.use(whatsappCoexistenceRoutes_1["default"]);
routes.use(whatsappOfficialRoutes_1["default"]);
routes.use(messageRoutes_1["default"]);
routes.use(whatsappSessionRoutes_1["default"]);
routes.use(queueRoutes_1["default"]);
routes.use(companyRoutes_1["default"]);
routes.use(planRoutes_1["default"]);
routes.use(ticketNoteRoutes_1["default"]);
routes.use(quickMessageRoutes_1["default"]);
routes.use(helpRoutes_1["default"]);
routes.use(dashboardRoutes_1["default"]);
routes.use(scheduleRoutes_1["default"]);
routes.use(tagRoutes_1["default"]);
routes.use(contactListRoutes_1["default"]);
routes.use(contactListItemRoutes_1["default"]);
routes.use(campaignRoutes_1["default"]);
routes.use(campaignSettingRoutes_1["default"]);
routes.use(announcementRoutes_1["default"]);
routes.use(chatRoutes_1["default"]);
routes.use(chatBotRoutes_1["default"]);
routes.use("/webhook", webHookRoutes_1["default"]);
routes.use(subScriptionRoutes_1["default"]);
routes.use(invoicesRoutes_1["default"]);
routes.use(faturasRoutes_1["default"]);
routes.use(versionRoutes_1["default"]);
routes.use(filesRoutes_1["default"]);
routes.use(queueOptionRoutes_1["default"]);
routes.use(queueIntegrationRoutes_1["default"]);
routes.use(ticketTagRoutes_1["default"]);
routes.use("/api", apiCompanyRoutes_1["default"]);
routes.use("/api", apiContactRoutes_1["default"]);
routes.use("/api", apiMessageRoutes_1["default"]);
routes.use("/api/external", externalClientRoutes_1["default"]);
routes.use("/api/external", externalContactRoutes_1["default"]);
routes.use("/api/external", externalTagRoutes_1["default"]);
routes.use("/api/external", externalProductRoutes_1["default"]);
routes.use("/api/external", externalProductCategoryRoutes_1["default"]);
routes.use("/api/external", externalServiceRoutes_1["default"]);
routes.use("/api/external", externalQueueRoutes_1["default"]);
routes.use("/api/external", externalNegocioRoutes_1["default"]);
routes.use("/api/external", externalTagKanbanRoutes_1["default"]);
routes.use("/api/external", externalProjectRoutes_1["default"]);
routes.use("/api/external", externalProjectTaskRoutes_1["default"]);
routes.use("/api/external", externalUserRoutes_1["default"]);
routes.use("/api/external", externalTicketRoutes_1["default"]);
routes.use("/api/external", externalWhatsappRoutes_1["default"]);
routes.use("/api/external", externalFaturaRoutes_1["default"]);
routes.use(forgotPasswordRoutes_1["default"]);
routes.use(flowDefaultRoutes_1["default"]);
routes.use(webHookRoutes_2["default"]);
routes.use(webhookListRoutes_1["default"]);
routes.use(flowBuilderRoutes_1["default"]);
routes.use(flowCampaignRoutes_1["default"]);
routes.use(promptRouter_1["default"]);
routes.use(knowledgeBaseRouter_1["default"]);
routes.use(iaWorkflowRoutes_1["default"]);
routes.use(statisticsRoutes_1["default"]);
routes.use(companySettingsRoutes_1["default"]);
routes.use(ScheduledMessagesRoutes_1["default"]);
routes.use("/api/imaginasoft", imaginasoftRoutes_1["default"]);
routes.use('/api/clinic', clinicChatRoutes_1["default"]);
routes.use(negocioRoutes_1["default"]);
routes.use(produtoRoutes_1["default"]);
routes.use(ferramentaRoutes_1["default"]);
routes.use(googleCalendarRoutes_1["default"]);
routes.use("/google-sheets", googleSheetsRoutes_1["default"]);
routes.use("/google-calendar", userGoogleCalendarRoutes_1["default"]);
routes.use("/user-google-calendar", userGoogleCalendarRoutes_1["default"]);
// routes.use("/mobile-webhook", mobileWebhookRoutes);
routes.use(emailRoutes_1["default"]);
routes.use("/tutorial-videos", tutorialVideoRoutes_1["default"]);
routes.use(sliderHomeRoutes_1["default"]);
routes.use(profissionalRoutes_1["default"]);
routes.use(servicoRoutes_1["default"]);
routes.use(crmLeadRoutes_1["default"]);
routes.use(crmClientRoutes_1["default"]);
routes.use(financeiroFaturaRoutes_1["default"]);
routes.use(financeiroPagamentoRoutes_1["default"]);
routes.use(financeiroCategoriaRoutes_1["default"]);
routes.use(financeiroDespesaRoutes_1["default"]);
routes.use(financeiroFornecedorRoutes_1["default"]);
routes.use(financeiroPagamentoDespesaRoutes_1["default"]);
routes.use(paymentSettingRoutes_1["default"]);
routes.use(integrationSettingRoutes_1["default"]);
routes.use(aiIntegrationRoutes_1["default"]);
routes.use(taskRoutes_1["default"]);
routes.use(emailAccountRoutes_1["default"]);
routes.use(companyApiKeyRoutes_1["default"]);
routes.use("/affiliate", affiliateRoutes_1["default"]);
routes.use("/coupon", couponRoutes_1["default"]);
routes.use(paymentGatewayWebhookRoutes_1["default"]);
routes.use(checkoutRoutes_1["default"]);
routes.use(asaasRoutes_1["default"]);
routes.use(scheduledDispatcherRoutes_1["default"]);
routes.use(projectRoutes_1["default"]);
routes.use(userScheduleRoutes_1["default"]);
routes.use(appointmentRoutes_1["default"]);
routes.use(followUpRoutes_1["default"]);
// Documentos da Empresa
routes.use("/company-documents", companyDocumentRoutes_1["default"]);
// API Externa de Login
routes.use("/api/external", externalApiRoutes_1["default"]);
// HubEcosystem
routes.use(hubChannelRoutes_1["default"]);
routes.use(hubMessageRoutes_1["default"]);
routes.use(hubWebhookRoutes_1["default"]);
routes.use(automationRoutes_1["default"]);
// OAuth Facebook/Instagram
routes.use(facebookOAuthRoutes_1["default"]);
// Google Meu Negócio
routes.use(googleBusinessRoutes_1["default"]);
// IA — Sugestão de resposta no chat
routes.use(aiSuggestionRoutes_1["default"]);
// Fiscal
routes.use(fiscalRoutes_1["default"]);
// Configurações e Analytics de Contatos
routes.use(contactSettingsRoutes_1["default"]);
routes.use(contactAnalyticsRoutes_1["default"]);
// Notificações Push
routes.use("/notifications", notificationRoutes_1["default"]);
// Histórico de Chamadas
routes.use(callRecordRoutes_1["default"]);
// Traduções
routes.use(translationRoutes_1["default"]);
// Ordem de Serviço
routes.use(serviceOrderRoutes_1["default"]);
// Hosti Notas
routes.use(hostiNotasRoutes_1["default"]);
// Permissões de Páginas
routes.use(userPagePermissionRoutes_1["default"]);
// Widget WhatsApp rastreável para sites externos
routes.use(whatsappWidgetRoutes_1["default"]);
routes.use(aiCreditsRoutes_1["default"]);
exports["default"] = routes;
